services:
  api:
    image: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-api
    container_name: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-api
    build:
      context: ../..
      dockerfile: Ddd.App.Api/Dockerfile
      args:
        GITHUBCFG_USERNAME: ${GITHUBCFG_USERNAME}
        GITHUBCFG_PAT: ${GITHUBCFG_PAT}
        GITHUBCFG_NAMESPACE: ${GITHUBCFG_NAMESPACE}
    volumes: [../Output/Log:/log]
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      APP_SUBDOMAIN: ${APP_SUBDOMAIN}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      EVENT_BUS_HOST: ${EVENT_BUS_HOST} 
      EVENT_BUS_USERNAME: ${EVENT_BUS_USERNAME}
      EVENT_BUS_PASSWORD: ${EVENT_BUS_PASSWORD}
      EVENT_BUS_PORT: ${EVENT_BUS_PORT}
    depends_on:
      - appdb
    networks:
      - tmpltnetwork
    extra_hosts:
    - "host.docker.internal:host-gateway"
  appdb:
    image: ghcr.io/documentdb/documentdb/documentdb-local:latest
    container_name: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-appdb
    restart: unless-stopped
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      APP_SUBDOMAIN: ${APP_SUBDOMAIN}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      APP_DB_PORT: 9712
      APP_DB_BACKUP_PATH: /usr/documentdb/backup
      APP_DB_SCRIPTS_PATH: /usr/documentdb/scripts
    ports:
      - "10260:10260"
    command:  ["--username", "$APP_DB_USERNAME", "--password", "$APP_DB_PASSWORD"]
    networks:
      - tmpltnetwork
  authentik-postgresql:
    env_file:
    - .env
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
    - database:/var/lib/postgresql/data
  authentik-server:
    command: server
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.0}
    ports:
    - ${COMPOSE_PORT_HTTP:-9000}:9000
    - ${COMPOSE_PORT_HTTPS:-9443}:9443
    restart: unless-stopped
    shm_size: 512mb
    volumes:
    - ./data:/data
    - ./custom-templates:/templates
  authentik-worker:
    command: worker
    depends_on:
      authentik-postgresql:
        condition: service_healthy
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.0}
    restart: unless-stopped
    shm_size: 512mb
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data:/data
    - ./certs:/certs
    - ./custom-templates:/templates
volumes:
  database:
    driver: local         
networks:
  tmpltnetwork:  