services:
  api:
    image: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-api
    container_name: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-api
    build:
      context: ../..
      dockerfile: Ddd.App.Api/Dockerfile
      args:
        GITHUBCFG_USERNAME: ${GITHUBCFG_USERNAME}
        GITHUBCFG_PAT: ${GITHUBCFG_PAT}
        GITHUBCFG_NAMESPACE: ${GITHUBCFG_NAMESPACE}
    volumes: [../Output/Log:/log]
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      APP_SUBDOMAIN: ${APP_SUBDOMAIN}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      EVENT_BUS_HOST: ${EVENT_BUS_HOST} 
      EVENT_BUS_USERNAME: ${EVENT_BUS_USERNAME}
      EVENT_BUS_PASSWORD: ${EVENT_BUS_PASSWORD}
      EVENT_BUS_PORT: ${EVENT_BUS_PORT}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
    depends_on:
      - appdb
    networks:
      - tmpltnetwork
    extra_hosts:
    - "host.docker.internal:host-gateway"
  web:
    image: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-web
    container_name: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-web
    build:
      context: ../..
      dockerfile: Ddd.App.Web/Ddd.App.Web/Dockerfile
      args:
        GITHUBCFG_USERNAME: ${GITHUBCFG_USERNAME}
        GITHUBCFG_PAT: ${GITHUBCFG_PAT}
        GITHUBCFG_NAMESPACE: ${GITHUBCFG_NAMESPACE}
    volumes: [../Output/Log:/log]
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      APP_SUBDOMAIN: ${APP_SUBDOMAIN}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      EVENT_BUS_HOST: ${EVENT_BUS_HOST}   
      EVENT_BUS_USERNAME: ${EVENT_BUS_USERNAME}
      EVENT_BUS_PASSWORD: ${EVENT_BUS_PASSWORD}
      EVENT_BUS_PORT: ${EVENT_BUS_PORT}
      AUTH_CLIENT_SECRET: ${AUTH_CLIENT_SECRET}
    depends_on:
      - appdb
    networks:
      - tmpltnetwork
    extra_hosts:
    - "host.docker.internal:host-gateway"
  appdb:
    image: ghcr.io/documentdb/documentdb/documentdb-local:latest
    container_name: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-appdb
    restart: unless-stopped
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      APP_SUBDOMAIN: ${APP_SUBDOMAIN}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      APP_DB_PORT: 9712
      APP_DB_BACKUP_PATH: /usr/documentdb/backup
      APP_DB_SCRIPTS_PATH: /usr/documentdb/scripts
    ports:
      - "10260:10260"
    command:  ["--username", "$APP_DB_USERNAME", "--password", "$APP_DB_PASSWORD"]
    networks:
      - tmpltnetwork
  auth:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-auth
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - tmpltnetwork
volumes:
  database:
    driver: local         
networks:
  tmpltnetwork:  