services:
  api:
    image: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-api
    container_name: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-api
    build:
      context: ..
      dockerfile: Api/Api/Dockerfile
      args:
        GITHUBCFG_USERNAME: ${GITHUBCFG_USERNAME}
        GITHUBCFG_PAT: ${GITHUBCFG_PAT}
        GITHUBCFG_NAMESPACE: ${GITHUBCFG_NAMESPACE}
    volumes: [../Output/Log:/log]
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      APP_SUBDOMAIN: ${APP_SUBDOMAIN}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      EVENT_BUS_HOST: ${EVENT_BUS_HOST} 
      EVENT_BUS_USERNAME: ${EVENT_BUS_USERNAME}
      EVENT_BUS_PASSWORD: ${EVENT_BUS_PASSWORD}
    depends_on:
      - appdb
    networks:
      - tmpltnetwork
    extra_hosts:
    - "host.docker.internal:host-gateway"
  appdb:
    image: ghcr.io/documentdb/documentdb/documentdb-local:latest
    container_name: ${DOCKER_REGISTRY-}${APP_DOMAIN}-${APP_SUBDOMAIN}-appdb
    restart: unless-stopped
    ports:
      - "10260:10260"
    command:  ["--username", "$APP_DB_USERNAME", "--password", "$APP_DB_PASSWORD"]
    networks:
      - tmpltnetwork

networks:
  tmpltnetwork:  