# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUBCFG_PAT: ${{ secrets.GITHUBCFG_PAT }}
      GITHUBCFG_NAMESPACE: ${{ secrets.GITHUBCFG_NAMESPACE }}
      GITHUBCFG_USERNAME: ${{ secrets.GITHUBCFG_USERNAME }}    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore ./Ddd.Api/Ddd.Api.sln
    - name: Build
      run: dotnet build --no-restore ./Ddd.Api/Ddd.Api.sln
    - name: Publish
      run: dotnet publish ./Ddd.Api/Ddd.Api.sln
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal ./Ddd.Api.UnitTests/Ddd.Api.UnitTests.csproj
        dotnet test --no-build --verbosity normal ./Ddd.App.UnitTests/Ddd.App.UnitTests.csproj
        
